### ISSUE TITLE
[Feature Request] ShadowSocks 新的加密方式 RC4-MD5

### ISSUE THREAD

**Issue by 70599** [ravageralpha/my_openwrt_mod#10]
可以在issues里发Feature Request吗？发错地方了的话请见谅。

ShadowSocks 新的加密方式 RC4-MD5。
传送门：http://www.v2ex.com/t/132519#reply98

shadowsocks-libev已跟进，希望RAMOD也更新一下相应组件。

**Comment by ravageralpha** [comment]
好的，更新了。

看 https://github.com/ravageralpha/my_openwrt_mod/commit/c8a6073d53ee491c56b221ee06b017be0698e4ae
