### ISSUE TITLE
可不可以增加luci-pdns？

### ISSUE THREAD

**Issue by yanest** [ravageralpha/my_openwrt_mod#12]
另外建议在luci-shadowsocks的设置页面上增加ipset的web设置选项，我在恩山的http://www.right.com.cn/forum/thread-139399-1-1.html 这个固件里面的shadowsocks有这个选项，很方便。

**Comment by ravageralpha** [comment]
pdnsd? 以前写了个简单 LuCI 支持不过现在删掉了，pdnsd 太臃肿，现在就用 chinadns 吧，或者可以用这里

https://github.com/ravageralpha/my_openwrt_mod/tree/2c463142266be1206db2ce8241c913eeaa350730/luci/applications/luci-pdnsd

luci-shadowsocks 已经添加 ipset 支持了，不明白你说的什么 web 设置选项。
