### ISSUE TITLE
luci:shadowsocks is running but Processes no run

### ISSUE THREAD

**Issue by crysisx** [ravageralpha/my_openwrt_mod#15]
PID USER       VSZ STAT COMMAND
    1 root      1408 S    /sbin/procd
    2 root         0 SW   [kthreadd]
    3 root         0 SW   [ksoftirqd/0]
    5 root         0 SW<  [kworker/0:0H]
    6 root         0 SW   [kworker/u2:0]
    7 root         0 SW<  [khelper]
   60 root         0 SW<  [writeback]
   61 root         0 SW<  [bioset]
   65 root         0 SW<  [kblockd]
   67 root         0 SW   [kswapd0]
   68 root         0 SW   [fsnotify_mark]
   69 root         0 SW   [kworker/0:1]
  153 root         0 SW   [spi0]
  244 root         0 SW<  [deferwq]
  245 root         0 SW   [kworker/u2:2]
  259 root         0 SW   [kworker/0:2]
  334 root         0 SWN  [jffs2_gcd_mtd3]
  392 root       892 S    /sbin/ubusd
  393 root       772 S    /sbin/askfirst /bin/ash --login
  528 root         0 SW<  [ipv6_addrconf]
  605 root         0 SW<  [cfg80211]
  709 root      1044 S    /sbin/logd -S 16
  718 root      1532 S    /sbin/rpcd
  751 root      1564 S    /sbin/netifd
  775 root      1160 S    /usr/sbin/odhcpd
  807 root      1152 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p
  846 root      2152 S    /usr/sbin/uhttpd -f -h /www -r OpenWrt -x /cgi-bin -
  853 root       832 S    chinadns -c /etc/chinadns_chnroute.txt -m -p 1053 -s
 1026 root      1360 S    udhcpc -p /var/run/udhcpc-eth0.pid -s /lib/netifd/dh
 1028 root       800 S    odhcp6c -s /lib/netifd/dhcpv6.script -P0 -t120 eth0
 1092 root      1640 S    /usr/sbin/hostapd -P /var/run/wifi-phy0.pid -B /var/
 1123 nobody     928 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf -k -x /va
 1136 root      1360 S    /usr/sbin/ntpd -n -S /usr/sbin/ntpd-hotplug -p 0.ope
 1305 root      1220 R    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p
 1306 root      1372 S    -ash
 1567 root      2568 S    /usr/bin/ss-local -b 0.0.0.0 -s xxxxxxxxxx -p 898
 1588 root      1360 R    ps

**Comment by crysisx** [comment]
root@OpenWrt:~# find / -name shadowsocks
/etc/config/shadowsocks
/etc/init.d/shadowsocks
/lib/upgrade/keep.d/shadowsocks
/overlay/upper/etc/config/shadowsocks
/rom/etc/config/shadowsocks
/rom/etc/init.d/shadowsocks
/rom/lib/upgrade/keep.d/shadowsocks
/rom/usr/share/shadowsocks
/usr/share/shadowsocks

**Comment by crysisx** [comment]
where is shadowsocks.log

**Comment by ravageralpha** [comment]
Too vague.

```
1567 root 2568 S /usr/bin/ss-local -b 0.0.0.0 -s xxxxxxxxxx -p 898
```

Currently i didn't enable the logging plus i don't see any problem here.
