### ISSUE TITLE
some simple error

### ISSUE THREAD

**Issue by hdume** [ravageralpha/my_openwrt_mod#18]
## ./scripts/feeds update -a && ./scripts/feeds install -a

WARNING: No feed for package 'kmod-mod-nat-extra' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'kmod-mod-tproxy' found, maybe it's already part of the standard packages?

---

is that lost some package?

**Comment by ravageralpha** [comment]
Nope, the warning said it all. 'kmod-mod-nat-extra' and 'kmod-mod-tproxy' already included in the standard packages, and luci-shadowsocks depends on it. You can just ignore this type of warning.
