### ISSUE TITLE
求助SS编译出错

### ISSUE THREAD

**Issue by wh0470** [ravageralpha/my_openwrt_mod#19]
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... no
checking whether pthreads work with -pthreads... no
checking whether pthreads work with -mthreads... no
checking for the pthreads library -lpthread... no
checking whether pthreads work with --thread-safe... no
checking whether pthreads work with -mt... no
checking for pthread-config... no
configure: error: Missing Pthread Library
make[3]: **\* [/home/wh/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/s-s-libev-git-openssl/s-s-libev-git-2.4.1/.configured_yyyyyyyyy] Error 1
make[3]: Leaving directory `/home/wh/openwrt/feeds/ramod/package/s-s-libev-git'
make[2]: *** [package/feeds/ramod/s-s-libev-git/compile] Error 2
make[2]: Leaving directory`/home/wh/openwrt'
make[1]: **\* [/home/wh/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/wh/openwrt'
make: **\* [world] 错误 2
wh@ubuntu:~/openwrt$

**Comment by shangjiyu** [comment]
我这边在Chaos_Calmer上也有这个问题，Trunk 上面则没有。修改 shadowsocks-openwrt官方的 release 包可以编译通过

``` makefile
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://github.com/shadowsocks/openwrt-shadowsocks/releases/download/v$(PKG_VERSION)
PKG_MD5SUM:=c3e03ebdad4b5678579503fbba8b0a8e
PKG_MAINTAINER:=Max Lv <max.c.lv@gmail.com>
```

**Comment by wh0470** [comment]
恩，我就是在CC上编的，谢谢你。

**Comment by ravageralpha** [comment]
修复了。

**Comment by wh0470** [comment]
非常感谢。

**Comment by wh0470** [comment]
ravageralpha：
还是不行，还是提示上面的错误。。15.05 CC
