### ISSUE TITLE
firewall issue

### ISSUE THREAD

**Issue by neroanelli** [ravageralpha/my_openwrt_mod#2]
如果有其他程序或者脚本触发了防火墙重启，那么 `shadowsocks` or `redsocks2`的防火墙规则将会丢失，只能重新启动程序。
而类似`mwan3`这样触发`firewall`的脚本，无法和`shadowsocks`共存。因为启用了`shadowsocks`，那么`mwan3`的`iptables`规则失效；而重启`mwan3`，则`shadowsocks`的`iptables`规则失效。

**Comment by ravageralpha** [comment]
这个已经考虑到了，看
https://github.com/ravageralpha/my_openwrt_mod/blob/RA-MOD/luci/libs/core/root/etc/config/ucitrack
在LuCI层面重启firewall的话会触发shadowsocks和redsocks2重启，但是如果其他程序init脚本触发防火墙的话这暂时无解，而且新版firewall的uci里支持设置ipset，但是不支持ip白名单这类的设置，或许在mwan里做下兼容应该可以，我没用过mwan，不清楚。

**Comment by neroanelli** [comment]
由于`ss-redir`和`redsocks2`关闭时会执行`fw3 -q restart`命令，防火墙重启会对造成一些程序的防火墙规则丢失。
部分程序是在**firewall**配置中添加了自定义脚本，比如`miniupnpd`

```
config include 'miniupnpd'
    option type 'script'
    option path '/usr/share/miniupnpd/firewall.include'
    option family 'IPv4'
    option reload '1'
```

所以暂时我对`shadowsocks`和`redsocks2`脚本的`stop`函数做了以下修改：

```
    iptables -t nat -F SHADOWSOCKS
    iptables -t nat -D zone_lan_prerouting -j SHADOWSOCKS
    iptables -t nat -X SHADOWSOCKS
    #fw3 -q restart
```

修改后，关闭`shadowsocks`和`redsocks2`不会重启防火墙。

**Comment by ravageralpha** [comment]
是的，直接重启防火墙确实会产生混乱，当初没考虑到，谢谢。

**Comment by jinwyp** [comment]
还是这个问题,
我在恩山写了一个帖子
http://www.right.com.cn/forum/thread-142002-1-1.html
1 问一下 redsock2 设置后 会添加iptable规则 REDSOCKS,  
是在root / etc / init.d / redsocks2 这个文件里面吗? 

2 能否加入 中国ip 地区的 一大堆的iptables 那个帖子里面有

3 如果通过luci 启动ss-redir 是否 与 会与redsock的规则链冲突? 还是需要关闭redsock2

**Comment by ravageralpha** [comment]
1, 是。
2, 已经加入ipset载入ip白名单功能，想要中国ip白名单的可以看看分支841v7里的ipset文件。
3, 会，redsocks 和 ss-redir 都是透明代理，两者只能开其中一个。
