### ISSUE TITLE
ota_enabled flag useless

### ISSUE THREAD

**Issue by shangjiyu** [ravageralpha/my_openwrt_mod#20]
貌似 [**ota_enabled**](https://github.com/ravageralpha/my_openwrt_mod/blob/RA-MOD/luci/applications/luci-shadowsocks/root/etc/init.d/shadowsocks) 选项勾不勾 都会加上-A 选项

``` shell
${ota_enabled:+-A} 
```

**ota_enabled** 只要定义了不管是0还是1都会加上**-A**？

另外 [**ipset/reserve**](https://github.com/ravageralpha/my_openwrt_mod/blob/RA-MOD/luci/applications/luci-shadowsocks/root/etc/ipset/reserve) 文件最后一行格式不对？

**Comment by ravageralpha** [comment]
好的，修复了。
https://github.com/ravageralpha/my_openwrt_mod/commit/efe650e1c55f231ae4825a5e13c23c402d347a9c
