### ISSUE TITLE
SS编译还是出错15.05CC

### ISSUE THREAD

**Issue by wh0470** [ravageralpha/my_openwrt_mod#21]
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... no
checking whether pthreads work with -pthreads... no
checking whether pthreads work with -mthreads... no
checking for the pthreads library -lpthread... no
checking whether pthreads work with --thread-safe... no
checking whether pthreads work with -mt... no
checking for pthread-config... no
configure: error: Missing Pthread Library
make[3]: **\* [/home/wh/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/s-s-libev-git-openssl/s-s-libev-git-2.4.1/.configured_yyyyyyyyy] Error 1
make[3]: Leaving directory /home/wh/openwrt/feeds/ramod/package/s-s-libev-git' make[2]: **\* [package/feeds/ramod/s-s-libev-git/compile] Error 2 make[2]: Leaving directory/home/wh/openwrt'
make[1]: **\* [/home/wh/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/wh/openwrt'
make: **\* [world] 错误 2
wh@ubuntu:~/openwrt$

修复后编译还是这个错误，请帮忙看看！

**Comment by ravageralpha** [comment]
./scripts/feeds update -a && ./scripts/feeds install -a && make clean

**Comment by imbeee** [comment]
同样仍存在这个问题
Ubuntu Server 14.04.3
gcc version 4.8.4
15.05CC, 非trunk
