### ISSUE TITLE
我们用移动的宽带，不能穿墙，但可以联网

### ISSUE THREAD

**Issue by crysisx** [ravageralpha/my_openwrt_mod#24]
chinadns和ss都启动了，系统日志和内核日志也没有报错，确定服务器没有问题，下面是进程，我应该如何定位问题呢，请大神指导，谢谢

root@OpenWrt:~# ps
  PID USER       VSZ STAT COMMAND
    1 root      1524 S    /sbin/procd
    2 root         0 SW   [kthreadd]
    3 root         0 SW   [ksoftirqd/0]
    5 root         0 SW<  [kworker/0:0H]
    6 root         0 SW   [kworker/u2:0]
    7 root         0 SW<  [khelper]
    8 root         0 SW   [kworker/u2:1]
   65 root         0 SW<  [writeback]
   67 root         0 SW<  [crypto]
   68 root         0 SW<  [bioset]
   70 root         0 SW<  [kblockd]
  100 root         0 SW   [kswapd0]
  101 root         0 SW   [kworker/0:1]
  150 root         0 SW   [fsnotify_mark]
  172 root         0 SW   [spi0]
  271 root         0 SW<  [ipv6_addrconf]
  277 root         0 SW<  [deferwq]
  280 root         0 SW<  [kworker/0:1H]
  326 root         0 SW   [kworker/0:2]
  357 root         0 SWN  [jffs2_gcd_mtd3]
  402 root      1168 S    /sbin/ubusd
  403 root       888 S    /sbin/askfirst /bin/ash --login
  606 root         0 SW<  [cfg80211]
  712 root      1168 S    /sbin/logd -S 16
  721 root      1432 S    /sbin/rpcd
  756 root      1688 S    /sbin/netifd
  770 root      1272 S    /usr/sbin/odhcpd
  810 root      1052 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p
  835 root      2180 S    /usr/sbin/uhttpd -f -h /www -r OpenWrt -x /cgi-bin -
 1037 root      1172 S    udhcpc -p /var/run/udhcpc-eth0.pid -s /lib/netifd/dh
 1039 root       912 S    odhcp6c -s /lib/netifd/dhcpv6.script -P0 -t120 eth0
 1128 root      1636 S    /usr/sbin/hostapd -P /var/run/wifi-phy0.pid -B /var/
 1190 root      1176 S    /usr/sbin/ntpd -n -S /usr/sbin/ntpd-hotplug -p 0.ope
 1351 root       952 S    /usr/bin/chinadns -c /etc/chinadns_chnroute.txt -m -
 1404 nobody    1048 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf -k -x /va
 1476 root      1120 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p
 1477 root      1180 S    -ash
 1609 root      2668 S    /usr/bin/ss-local -b 0.0.0.0 -s 45.32.24.249 -p 6379
 1621 root      1172 R    ps
root@OpenWrt:~#

**Comment by ravageralpha** [comment]
This is not issue about my mod, learn how to read the ps list first.
