### ISSUE TITLE
 shadowsocks luci --Forwarding Tunnel 这个是什么，怎么配置，什么时候需要

### ISSUE THREAD

**Issue by crysisx** [ravageralpha/my_openwrt_mod#26]
Forwarding Tunnel 这个是什么，怎么配置，什么时候需要
![image](https://cloud.githubusercontent.com/assets/7436762/19415421/4f4e5544-93a2-11e6-94bf-9af49c17397a.png)

**Comment by ravageralpha** [comment]
转发端口用的, 这功能一般用在 DNS 查询上, 以上图为例, 如果 DNS 地址设置为 127.0.0.1:5353 则通过 shadowsocks 服务器查询 8.8.8.8:53 然后转发回本地端口.

**Comment by crysisx** [comment]
thanks
