### ISSUE TITLE
now not support ss ，how to climb over the wall

### ISSUE THREAD

**Issue by crysisx** [ravageralpha/my_openwrt_mod#27]
how to select luci RA-mod

**Comment by crysisx** [comment]
Clibc-0.9.33.2_eabi/root-mvebu/tmp-ip/etc/iproute2
install -m0755 /root/openwrt/build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/iproute2-tiny/iproute2-4.0.0/ip/ip /root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/root-mvebu/tmp-ip/usr/sbin/
SHELL= /root/openwrt/staging_dir/host/bin/flock /root/openwrt/tmp/.root-copy.flock -c 'cp -fpR /root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/root-mvebu/tmp-ip/. /root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/root-mvebu/'
rm -rf /root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/root-mvebu/tmp-ip
touch /root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/root-mvebu/stamp/.ip_installed
if [ -f /root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/iproute2.tiny.install.clean ]; then rm -f /root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/iproute2.tiny.install /root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/iproute2.tiny.install.clean; fi; echo "ip" >> /root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/iproute2.tiny.install
make[3]: Leaving directory `/root/openwrt/package/network/utils/iproute2'
make[3]: Entering directory `/root/openwrt/feeds/ramod/package/ShadowVPN'
make[3]: Leaving directory `/root/openwrt/feeds/ramod/package/ShadowVPN'
make[3]: Entering directory `/root/openwrt/feeds/ramod/package/tun2socks'
mkdir -p /root/openwrt/bin/mvebu/packages /root/openwrt/build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/tun2socks/badvpn-1.999.130.1/ipkg-mvebu/tun2socks/CONTROL /root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/pkginfo
install -d -m0755 /root/openwrt/build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/tun2socks/badvpn-1.999.130.1/ipkg-mvebu/tun2socks/usr/bin
install -m0755 /root/openwrt/build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/tun2socks/badvpn-1.999.130.1/tun2socks/badvpn-tun2socks /root/openwrt/build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/tun2socks/badvpn-1.999.130.1/ipkg-mvebu/tun2socks/usr/bin/tun2socks
find /root/openwrt/build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/tun2socks/badvpn-1.999.130.1/ipkg-mvebu/tun2socks -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package tun2socks is missing dependencies for the following libraries:
libpthread.so.0
librt.so.0
make[3]: *** [/root/openwrt/bin/mvebu/packages/ramod/tun2socks_1.999.130.1_mvebu.ipk] Error 1
make[3]: Leaving directory `/root/openwrt/feeds/ramod/package/tun2socks'
make[2]: *** [package/feeds/ramod/tun2socks/compile] Error 2
make[2]: Leaving directory `/root/openwrt'
make[1]: *** [/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory `/root/openwrt'
make: *** [world] Error 2

**Comment by ravageralpha** [comment]
You can just use the shadowsocks officical for better support.
