### ISSUE TITLE
已挂载U盘，但是luci-app-aria2显示“aria2未运行，请确保已挂载USB存储设备”

### ISSUE THREAD

**Issue by 70599** [ravageralpha/my_openwrt_mod#6]
已挂载U盘，但是luci-app-aria2显示“aria2未运行，请确保已挂载USB存储设备”。
而且luci-app-aria2页面的“设备”项的下拉菜单没有可选项目（显示为空白）。

Model
Buffalo WZR-HP-AG300H/WZR-600DHP

固件版本
OpenWrt Chaos Calmer r42332 / LuCI Trunk (git-822e19f)

内核版本
3.10.49

**Comment by ravageralpha** [comment]
U盘什么文件系统？确认已挂载了吗？SSH 进入能正常访问U盘吗？

**Comment by 70599** [comment]
U盘是EXT4文件系统，挂载情况请看下面截图：
http://i.share.pho.to/28c47ce0_o.png

ssh访问正常，可以创建、删除目录，具体情况请看下面截图：
http://i.share.pho.to/3337bb0a_o.png

luci-app-aria2在已确认上述情况后，设备项依然是空白，截图：
http://i.share.pho.to/630608c7_o.png

已尝试make dirclean后编译，无效。

**Comment by ravageralpha** [comment]
你的分区表不正常，一般/dev/sda只是表示设备名，分区名应该是类似/dev/sda1，估计你是还没有分区就格式化了U盘，想修改可以，不过就没那么规范了。

https://github.com/ravageralpha/my_openwrt_mod/blob/RA-MOD/luci/applications/luci-aria2/luasrc/model/cbi/aria2.lua#L27

删掉一个问号就可以显示，建议你重新格式化你的U盘。

**Comment by 70599** [comment]
感谢回复，重新分区后问题解决。
