### ISSUE TITLE
my_openwrt_mod  make error

### ISSUE THREAD

**Issue by crysisx** [ravageralpha/my_openwrt_mod#7]
1.4版本在 AR71XX的cpu 在最新opewrt的trunk主干
编译跳错误：
make[4]: Entering directory `/home/openwrt/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-1.4'
make all-recursive
make[5]: Entering directory`/home/openwrt/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-1.4'
Making all in libasyncns
make[6]: Entering directory `/home/openwrt/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-1.4/libasyncns'
/bin/bash ../libtool --tag=CC --mode=compile mips-openwrt-linux-uclibc-gcc -DHAVE_CONFIG_H -I. -I.. -I/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include -D__EXTENSIONS__ -pthread -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -MT asyncns.lo -MD -MP -MF .deps/asyncns.Tpo -c -o asyncns.lo asyncns.c
OpenWrt-libtool: compile: mips-openwrt-linux-uclibc-gcc -DHAVE_CONFIG_H -I. -I.. -I/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include -D__EXTENSIONS__ -pthread -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -MT asyncns.lo -MD -MP -MF .deps/asyncns.Tpo -c asyncns.c -fPIC -DPIC -o .libs/asyncns.o
OpenWrt-libtool: compile: mips-openwrt-linux-uclibc-gcc -DHAVE_CONFIG_H -I. -I.. -I/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include -D__EXTENSIONS__ -pthread -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -MT asyncns.lo -MD -MP -MF .deps/asyncns.Tpo -c asyncns.c -o asyncns.o >/dev/null 2>&1
mv -f .deps/asyncns.Tpo .deps/asyncns.Plo
/bin/bash ../libtool --tag=CC --mode=link mips-openwrt-linux-uclibc-gcc -D__EXTENSIONS__ -pthread -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -static -L/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -L/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/lib -L/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib -o libasyncns.la asyncns.lo -lcrypto -lm
OpenWrt-libtool: link: mips-openwrt-linux-uclibc-ar cru .libs/libasyncns.a asyncns.o
OpenWrt-libtool: link: mips-openwrt-linux-uclibc-ranlib .libs/libasyncns.a
OpenWrt-libtool: link: ( cd ".libs" && rm -f "libasyncns.la" && ln -s "../libasyncns.la" "libasyncns.la" )
make[6]: Leaving directory`/home/openwrt/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-1.4/libasyncns'
Making all in libev
make[6]: Entering directory `/home/openwrt/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-1.4/libev'
/bin/bash ../libtool --tag=CC --mode=compile mips-openwrt-linux-uclibc-gcc -DHAVE_CONFIG_H -I. -I.. -I/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -MT ev.lo -MD -MP -MF .deps/ev.Tpo -c -o ev.lo ev.c
OpenWrt-libtool: compile: mips-openwrt-linux-uclibc-gcc -DHAVE_CONFIG_H -I. -I.. -I/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -MT ev.lo -MD -MP -MF .deps/ev.Tpo -c ev.c -fPIC -DPIC -o .libs/ev.o
ev.c:1531:31: warning: 'ev_default_loop_ptr' initialized and declared 'extern' [enabled by default]
EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
^
{standard input}: Assembler messages:
{standard input}:756: Error: unrecognized opcode`sync'
{standard input}:766: Error: unrecognized opcode `sync'
{standard input}:772: Error: unrecognized opcode`sync'
{standard input}:781: Error: unrecognized opcode `sync'
{standard input}:3656: Error: unrecognized opcode`sync'
{standard input}:3747: Error: unrecognized opcode `sync'
{standard input}:3819: Error: unrecognized opcode`sync'
{standard input}:3831: Error: unrecognized opcode `sync'
{standard input}:3842: Error: unrecognized opcode`sync'
{standard input}:3885: Error: unrecognized opcode `sync'
{standard input}:8707: Error: unrecognized opcode`sync'
{standard input}:8752: Error: unrecognized opcode `sync'
{standard input}:9788: Error: unrecognized opcode`sync'
make[6]: **\* [ev.lo] Error 1
make[6]: Leaving directory `/home/openwrt/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-1.4/libev'
Making all in src

/////////////////
cache.c: In function 'cache_lookup':
cache.c:132:9: warning: implicit declaration of function 'strnlen' [-Wimplicit-function-declaration]
size_t key_len = strnlen(tmp->key, KEY_MAX_LENGTH);
^
cache.c:122:9: warning: unused variable 'rv' [-Wunused-variable]
int rv;
^
cache.c: In function 'cache_insert':
cache.c:163:9: warning: unused variable 'rv' [-Wunused-variable]
int rv;
^
mv -f .deps/ss_local-cache.Tpo .deps/ss_local-cache.Po
mips-openwrt-linux-uclibc-gcc -DHAVE_CONFIG_H -I. -I.. -I/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include -g -O2 -Wall -fno-strict-aliasing -I../libev -I../libasyncns -DUDPRELAY_LOCAL -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -MT ss_local-local.o -MD -MP -MF .deps/ss_local-local.Tpo -c -o ss_local-local.o `test -f 'local.c' || echo './'`local.c
local.c: In function 'main':
local.c:949:9: warning: implicit declaration of function 'udprelay_init' [-Wimplicit-function-declaration]
udprelay_init(local_addr, local_port, remote_host[0], remote_port, m, iface);
^
mv -f .deps/ss_local-local.Tpo .deps/ss_local-local.Po
make[6]: **\* No rule to make target `../libev/libev.la', needed by`ss-local'. Stop.
make[6]: Leaving directory `/home/openwrt/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-1.4/src'
make[6]: Entering directory`/home/openwrt/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-1.4'
make[6]: Leaving directory `/home/openwrt/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-1.4'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory`/home/openwrt/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-1.4'
make[4]: **\* [all] Error 2
make[4]: Leaving directory `/home/openwrt/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-1.4'
make[3]: *** [/home/openwrt/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-1.4/.built] Error 2
make[3]: Leaving directory`/home/openwrt/openwrt/package/shadowsocks-libev'
make[2]: **\* [package/shadowsocks-libev/compile] Error 2
make[2]: Leaving directory `/home/openwrt/openwrt'
make[1]: *** [/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory`/home/openwrt/openwrt'
make: **\* [world] Error 2

**Comment by ravageralpha** [comment]
我这无法重现，opcode 问题早已修复，检查是否用 GCC 4.8 以及你的 shadowsocks-libev 的 Makefile 是否有这行。 

**PKG_USE_MIPS16:=0**

相关:
https://dev.openwrt.org/ticket/14939
