### ISSUE TITLE
luci problem 

### ISSUE THREAD

**Issue by crysisx** [ravageralpha/my_openwrt_mod#9]
i copy  my_openwrt_mod to my openwrt  Catalog
like this
－－－－－－－－－－－－
＃cp -rf ./my_openwrt_mod/luci/\* openwrt/feeds/luci/
－－－－－－－－－－－－
but then my make  menuconfig 
 no  luci    Options in  menu

**Comment by ravageralpha** [comment]
Do as README said.

Also run:

> ./scripts/feed update -a && ./scripts/feed install -a

**Comment by crysisx** [comment]
is not run
#./scripts/feed update -a && ./scripts/feed install -a 
in  new  vision  of openwrt trunk  ,you had better run

# ./scripts/feeds update -a && ./scripts/feeds install -a

add i try uninstall luci before  execute this command
#./scripts/feeds update -a && ./scripts/feeds install -a

then i choose luci meun config execute make V=99  -j 5 ，
pass make!

but the chinadns  can not run
